export const Typography = {
  h1: { fontSize: 24, fontWeight: "700" as const, letterSpacing: -0.3 },
  h2: { fontSize: 20, fontWeight: "700" as const, letterSpacing: -0.2 },
  h3: { fontSize: 17, fontWeight: "700" as const },
  title: { fontSize: 15, fontWeight: "600" as const },
  body: { fontSize: 14, fontWeight: "400" as const },
  bodyMedium: { fontSize: 14, fontWeight: "500" as const },
  caption: { fontSize: 12, fontWeight: "400" as const },
  captionMedium: { fontSize: 12, fontWeight: "600" as const },
  label: { fontSize: 11, fontWeight: "600" as const, letterSpacing: 0.6 },
  price: { fontSize: 18, fontWeight: "700" as const },
  priceLarge: { fontSize: 22, fontWeight: "800" as const },
  countdownNumber: { fontSize: 26, fontWeight: "800" as const, letterSpacing: -0.5 },
  button: { fontSize: 15, fontWeight: "700" as const },
};
